<<<<<<< HEAD
---
# tasks file for ansible-role-upgrade

- name: Ensure Dependencies are present.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - dnf
    - dnf-utils
  tags: upgrade

- name: Mark packages on hold {{ upgrade_packages_on_hold }}
  ansible.builtin.command:
    cmd: "dnf versionlock add {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Upgrade via dnf module
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  tags: upgrade

- name: Remove packages on hold
  ansible.builtin.command:
    cmd: "dnf versionlock delete {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Clean dnf cache
  ansible.builtin.dnf:
    autoremove: yes
  tags: upgrade

- name: Check for Reboot Hint
  ansible.builtin.command:
    cmd: "dnf needs-restarting -r"
  register: needs_restarting
  changed_when: needs_restarting.rc == 1
  failed_when: needs_restarting.rc == 0 and needs_restarting.changed is true
  tags: upgrade
=======
---
# tasks file for ansible-role-upgrade

- name: Ensure Dependencies are present.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - dnf
    - dnf-utils
  tags: upgrade

- name: Mark packages on hold {{ upgrade_packages_on_hold }}
  ansible.builtin.command:
    cmd: "dnf versionlock add {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Upgrade via dnf module
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes
  tags: upgrade

- name: Remove packages on hold
  ansible.builtin.command:
    cmd: "dnf versionlock delete {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Clean dnf cache
  ansible.builtin.dnf:
    autoremove: yes
  tags: upgrade

- name: Check for Reboot Hint
  ansible.builtin.command:
    cmd: "dnf needs-restarting -r"
  register: needs_restarting
  changed_when: needs_restarting.rc == 1
  failed_when: needs_restarting.rc == 0
  tags: upgrade
>>>>>>> parent of e667dff (initial commit)
