---
# tasks file for ansible-role-upgrade

- name: Include pre-checks tasks
  ansible.builtin.include_tasks: pre-checks.yml
  tags: upgrade

- name: Include Package Manager specific Playbook
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: upgrade

- name: Include post-checks tasks
  ansible.builtin.include_tasks: post-checks.yml
  tags: upgrade
