---
# tasks file for ansible-role-upgrade

- name: Ensure Dependencies are present.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - yum
    - yum-utils
  tags: upgrade

- name: Mark packages on hold {{ upgrade_packages_on_hold }}
  community.general.yum_versionlock:
    name: "{{ item }}"
    state: present
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Upgrade via yum module
  ansible.builtin.dnf:
    name: "*"
    state: present
    update_cache: yes
    update_only: yes
  tags: upgrade

- name: Remove packages on hold
  community.general.yum_versionlock:
    name: "{{ item }}"
    state: absent
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Clean yum cache
  ansible.builtin.dnf:
    autoremove: yes
  tags: upgrade

- name: Check for Reboot Hint
  ansible.builtin.command:
    cmd: "dnf needs-restarting -r"
  register: needs_restarting
  changed_when: needs_restarting.rc == 1
  failed_when: needs_restarting.rc == 0 and needs_restarting.changed is true
  tags: upgrade
