---
# tasks file for ansible-role-upgrade

- name: Ensure Dependencies are present.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - yum
    - yum-utils
  tags: upgrade

- name: Mark packages on hold {{ upgrade_packages_on_hold }}
  ansible.builtin.command:
    cmd: "yum versionlock add {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Upgrade via yum module
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: yes
  tags: upgrade

- name: Remove packages on hold
  ansible.builtin.command:
    cmd: "yum versionlock delete {{ item }}"
  loop: "{{ upgrade_packages_on_hold }}"
  tags: upgrade

- name: Clean yum cache
  ansible.builtin.yum:
    autoremove: yes
  tags: upgrade

- name: Check for Reboot Hint
  ansible.builtin.command:
    cmd: "yum needs-restarting -r"
  register: reboot_hint
  changed_when: reboot_hint.stdout != ""
  failed_when: reboot_hint.rc != 0
  tags: upgrade
  