---
- name: Converge
  hosts: all
  vars:
    test_user: vagrant
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
    - name: Wait for systemd to complete initialization
      ansible.builtin.systemd:
        name: systemd-logind
      register: systemd_status
      until: systemd_status.status.ActiveState == "active"
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false

  roles:
    - role: iamenr0s.ansible_role_upgrade
