---
- name: Converge
  hosts: all
  become: false
  gather_facts: false

  pre_tasks:
    - name: Bootstrap Python 3 if missing (raw)
      ansible.builtin.raw: >
        bash -lc '
        if ! command -v python3 >/dev/null 2>&1; then
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update -y && apt-get install -y python3;
          elif command -v dnf >/dev/null 2>&1; then
            dnf -y install python3 || dnf -y install python39;
          elif command -v yum >/dev/null 2>&1; then
            yum -y install python3 || yum -y install python36;
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache python3;
          fi
        fi'
      changed_when: false

    - name: Create temp directory (raw)
      ansible.builtin.raw: >
        bash -lc 'mkdir -p /tmp/ansible-tmp && chmod 0777 /tmp/ansible-tmp'
      changed_when: false

    - name: Reset connection to pick up Python
      ansible.builtin.meta: reset_connection

  roles:
    - role: ../../
      name: upgrade
