---
- name: Converge
  hosts: all
  vars:
    remote_user: vagrant
  become: true
  become_method: sudo

  pre_tasks:
    - name: Wait for systemd to complete initialization
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: ../../
      name: upgrade
