---
- name: Converge
  hosts: all
  become: false
  gather_facts: false

  pre_tasks:
    - name: Create temp directory
      ansible.builtin.file:
        path: /tmp/ansible-tmp
        state: directory
        mode: '0777'

  roles:
    - role: ../../
      name: upgrade
