---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Check if instance config exists
      ansible.builtin.stat:
        path: "{{ molecule_instance_config }}"
      register: instance_config_stat

    - name: Prepare VMs config
      block:
        - name: Prepare VMs config
          ansible.builtin.set_fact:
            instance_conf: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
      when: instance_config_stat.stat.exists

    - name: Destroy molecule instance(s)
      qemu_vm:
        name: "{{ item.instance }}"
        state: absent
      register: server
      with_items: "{{ instance_conf | default([]) }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: qemu_jobs
      until: qemu_jobs.finished
      retries: 300
      delay: 2
      with_items: "{{ server.results | default([]) }}"

    - name: Remove instance config file
      ansible.builtin.file:
        path: "{{ molecule_instance_config }}"
        state: absent
      when: instance_config_stat.stat.exists