---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: vagrant
  provider:
    name: libvirt
  config_options:
    defaults:
      remote_user: vagrant
    ssh_connection:
      ssh_args: -o StrictHostKeyChecking=no -o User=vagrant
      pipelining: true
      timeout: 300
platforms:
  - name: instance
    box: generic/fedora38
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
