---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: podman
platforms:
  - name: instance
    image: "iamenr0s/docker-${MOLECULE_DISTRO:-almalinux9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible-${USER}/tmp
  config_options:
    defaults:
      host_key_checking: false
      remote_tmp: /tmp/.ansible-${USER}/tmp
      interpreter_python: auto_silent
