---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/.ansible-root/tmp
        state: directory
        mode: '0777'
      ignore_errors: true