---
- name: Prepare
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Ensure /tmp exists with correct permissions
      ansible.builtin.file:
        path: /tmp
        state: directory
        mode: '0777'
      ignore_errors: true