---

name: Release
on:
  workflow_run:
    workflows: ['Molecule']
    types:
      - completed
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths-ignore:
      - '**/*.md'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: 'Release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}